# AUTOMATICALLY GENERATED by https://github.com/tqdm/shtab
# Usage:
# 1) Copy this to somewhere (e.g. ~\.config\powershell\completions\rns-page-node.ps1
# 2) Add the following line to your $PROFILE:
#    . ~\.config\powershell\completions\rns-page-node.ps1
# See also: https://learn.microsoft.com/en-us/powershell/scripting/learn/shell/creating-profiles#adding-customizations-to-your-profile


# --- Completion data ---
$_shtab_rns_page_node_subparsers = @{}
$_shtab_rns_page_node_option_strings = @{
    '_shtab_rns_page_node' = @('-h', '--help', '-c', '--config', '-p', '--pages-dir', '-f', '--files-dir', '-m', '--media-dir', '-n', '--node-name', '-a', '--announce-interval', '-i', '--identity-dir', '--page-refresh-interval', '--file-refresh-interval', '-l', '--log-level')
}
$_shtab_rns_page_node_compgens = @{}
$_shtab_rns_page_node_choices = @{
    '_shtab_rns_page_node___log_level' = @('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL')
    '_shtab_rns_page_node__l' = @('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL')
}
$_shtab_rns_page_node_nargs = @{
    '_shtab_rns_page_node___help' = '0'
    '_shtab_rns_page_node__h' = '0'
}
$_shtab_rns_page_node_help = @{
    '_shtab_rns_page_node___announce_interval' = 'Announce interval in minutes'
    '_shtab_rns_page_node___config' = 'Reticulum config path'
    '_shtab_rns_page_node___file_refresh_interval' = 'File refresh interval in seconds, 0 disables auto-refresh'
    '_shtab_rns_page_node___files_dir' = 'Files directory'
    '_shtab_rns_page_node___help' = 'show this help message and exit'
    '_shtab_rns_page_node___identity_dir' = 'Directory to store node identity'
    '_shtab_rns_page_node___log_level' = 'Logging level'
    '_shtab_rns_page_node___media_dir' = 'Media directory for images, defaults to pages directory'
    '_shtab_rns_page_node___node_name' = 'Node display name'
    '_shtab_rns_page_node___page_refresh_interval' = 'Page refresh interval in seconds, 0 disables auto-refresh'
    '_shtab_rns_page_node___pages_dir' = 'Pages directory'
    '_shtab_rns_page_node__a' = 'Announce interval in minutes'
    '_shtab_rns_page_node__c' = 'Reticulum config path'
    '_shtab_rns_page_node__f' = 'Files directory'
    '_shtab_rns_page_node__h' = 'show this help message and exit'
    '_shtab_rns_page_node__i' = 'Directory to store node identity'
    '_shtab_rns_page_node__l' = 'Logging level'
    '_shtab_rns_page_node__m' = 'Media directory for images, defaults to pages directory'
    '_shtab_rns_page_node__n' = 'Node display name'
    '_shtab_rns_page_node__p' = 'Pages directory'
    '_shtab_rns_page_node_pos_0' = 'Path to rns-page-node config file'
}

# --- Helper functions ---

function _shtab_powershell_compgen_files {
  param([string]$WordToComplete)
  $dir = ''
  if ($WordToComplete -match '^(.*[\\/])') { $dir = $Matches[1] }
  Get-ChildItem -Path "$WordToComplete*" -File -ErrorAction SilentlyContinue |
    ForEach-Object { $dir + $_.Name }
  Get-ChildItem -Path "$WordToComplete*" -Directory -ErrorAction SilentlyContinue |
    ForEach-Object { $dir + $_.Name + [System.IO.Path]::DirectorySeparatorChar }
}

function _shtab_powershell_compgen_dirs {
  param([string]$WordToComplete)
  $dir = ''
  if ($WordToComplete -match '^(.*[\\/])') { $dir = $Matches[1] }
  Get-ChildItem -Path "$WordToComplete*" -Directory -ErrorAction SilentlyContinue |
    ForEach-Object { $dir + $_.Name + [System.IO.Path]::DirectorySeparatorChar }
}

function _shtab_powershell_replace_nonword {
  param([string]$Text)
  $Text -replace '[^\w]', '_'
}

# --- Main completer ---

Register-ArgumentCompleter -Native -CommandName rns-page-node -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)

  # Tokenize the command line (skip program name)
  $allTokens = @()
  if ($commandAst.CommandElements.Count -gt 1) {
    $allTokens = @($commandAst.CommandElements[1..($commandAst.CommandElements.Count - 1)] |
      ForEach-Object { $_.ToString() })
  }

  # Determine which tokens are "completed" (before the word being typed)
  # The last token is the one currently being completed if it matches wordToComplete
  $tokens = @()
  if ($allTokens.Count -gt 0) {
    if ($wordToComplete -and $allTokens[-1] -eq $wordToComplete) {
      if ($allTokens.Count -gt 1) {
        $tokens = $allTokens[0..($allTokens.Count - 2)]
      }
    } else {
      $tokens = $allTokens
    }
  }

  # State tracking
  $prefix = '_shtab_rns_page_node'
  $completedPositionals = 0
  $currentActionKey = "${prefix}_pos_0"
  $currentActionNargs = 1
  $currentActionArgsConsumed = 0
  $currentActionIsPositional = $true
  $posOnly = $false

  # Helper: look up nargs for a given action key (default 1)
  function Get-ActionNargs($actionKey) {
    $n = $_shtab_rns_page_node_nargs[$actionKey]
    if ($n) { return $n } else { return '1' }
  }

  # Helper: look up help text for a given action key (empty if none)
  function Get-ActionHelp($actionKey) {
    return $_shtab_rns_page_node_help[$actionKey]
  }

  # Walk completed tokens to determine current parser state
  foreach ($token in $tokens) {
    if ($posOnly -or $token -ne '--') {
      # Check for subparser match
      $currentSubparsers = $_shtab_rns_page_node_subparsers[$prefix]
      if ($currentSubparsers -and $currentSubparsers -contains $token) {
        $prefix = $prefix + '_' + (_shtab_powershell_replace_nonword $token)
        $completedPositionals = 0
        $currentActionKey = "${prefix}_pos_0"
        $currentActionNargs = Get-ActionNargs $currentActionKey
        $currentActionArgsConsumed = 0
        $currentActionIsPositional = $true
        continue
      }
      # Check for option string match
      $currentOptions = $_shtab_rns_page_node_option_strings[$prefix]
      if ($currentOptions -and $currentOptions -contains $token) {
        $currentActionKey = $prefix + '_' + (_shtab_powershell_replace_nonword $token)
        $currentActionNargs = Get-ActionNargs $currentActionKey
        $currentActionArgsConsumed = 0
        $currentActionIsPositional = $false
        continue
      }
      # Consume argument for current action
      $currentActionArgsConsumed++
      if ($currentActionNargs -ne '*' -and
        $currentActionNargs -ne '+' -and
        $currentActionNargs -ne '?' -and
        $currentActionNargs -notlike '*...*') {
        if ($currentActionArgsConsumed -ge [int]$currentActionNargs) {
          if ($currentActionIsPositional) { $completedPositionals++ }
          $currentActionKey = "${prefix}_pos_${completedPositionals}"
          $currentActionNargs = Get-ActionNargs $currentActionKey
          $currentActionArgsConsumed = 0
          $currentActionIsPositional = $true
        }
      }
    } else {
      $posOnly = $true
    }
  }
  # --- Generate completions ---
  if ($env:SHTAB_DEBUG -eq 'true') {
    Write-Host "shtab: wordToComplete='$wordToComplete' prefix='$prefix' `
    actionKey='$currentActionKey' isPositional='$currentActionIsPositional' posOnly='$posOnly'"
  }

  $completions = @()

  if (-not $posOnly -and $wordToComplete -like '-*') {
    # Complete option strings, tooltipped with each option's own help text
    $opts = $_shtab_rns_page_node_option_strings[$prefix]
    if ($opts) {
      foreach ($opt in $opts) {
        if ($opt -like "$wordToComplete*") {
          $optKey = $prefix + '_' + (_shtab_powershell_replace_nonword $opt)
          $completions += , @{Text = $opt; Tooltip = Get-ActionHelp $optKey}
        }
      }
    }
  } else {
    # Complete subparsers (only when current action is positional),
    # tooltipped with each subcommand's own help text
    if ($currentActionIsPositional) {
      $subs = $_shtab_rns_page_node_subparsers[$prefix]
      if ($subs) {
        foreach ($sub in $subs) {
          if ($sub -like "$wordToComplete*") {
            $subKey = $prefix + '_' + (_shtab_powershell_replace_nonword $sub)
            $completions += , @{Text = $sub; Tooltip = Get-ActionHelp $subKey}
          }
        }
      }
    }

    $actionHelp = Get-ActionHelp $currentActionKey

    # Complete choices for current action (positional or option)
    $actionChoices = $_shtab_rns_page_node_choices[$currentActionKey]
    if ($actionChoices) {
      foreach ($choice in $actionChoices) {
        if ($choice -like "$wordToComplete*") {
          $completions += , @{Text = $choice; Tooltip = $actionHelp}
        }
      }
    }
    # Complete using compgen function for current action
    $actionCompgen = $_shtab_rns_page_node_compgens[$currentActionKey]
    if ($actionCompgen) {
      foreach ($item in @(& $actionCompgen $wordToComplete)) {
        $completions += , @{Text = $item; Tooltip = $actionHelp}
      }
    }
  }
  # Deduplicate (by text) and emit CompletionResult objects
  $seen = New-Object System.Collections.Generic.HashSet[string]
  $results = @()
  foreach ($c in $completions) {
    if ($seen.Add($c.Text)) {
      $tooltip = if ($c.Tooltip) { $c.Tooltip } else { $c.Text }
      $results += [System.Management.Automation.CompletionResult]::new(
        $c.Text,          # completionText
        $c.Text,          # listItemText
        'ParameterValue',  # resultType
        $tooltip          # toolTip
      )
    }
  }
  # Prevent fallback file-path completion (PowerShell/PowerShell#19628)
  if ($results.Count -eq 0) { return $null }
  $results
}
