# AUTOMATICALLY GENERATED by https://github.com/tqdm/shtab
# Usage:
# 1) Copy this to ~/.config/fish/completions/rns-page-node.fish
# 2) Ensure a binary named rns-page-node is in your PATH
# See also: https://fishshell.com/docs/current/completions.html#where-to-put-completions


# Parse current commandline:
# - _shtab_rns_page_node_cmdpath=(sub)command path seen so far
# - _shtab_rns_page_node_npos=number of positional arguments given after it
# - options are skipped based on _shtab_rns_page_node_opts_with_value & _shtab_rns_page_node_commands lists
function _shtab_rns_page_node_scan
  set -g _shtab_rns_page_node_cmdpath ''
  set -g _shtab_rns_page_node_npos 0
  set -l tokens (commandline -opc)
  set -e tokens[1]
  set -l expect_value 0
  for t in $tokens
    if test $expect_value -eq 1
      set expect_value 0
      continue
    end
    switch "$t"
      case '--*=*'
        continue
      case '-*'
        if contains -- $t $_shtab_rns_page_node_opts_with_value
          set expect_value 1
        end
        continue
      case '*'
        if test $_shtab_rns_page_node_npos -eq 0
          set -l candidate $t
          if test -n "$_shtab_rns_page_node_cmdpath"
            set candidate "$_shtab_rns_page_node_cmdpath $t"
          end
          if contains -- $candidate $_shtab_rns_page_node_commands
            set -g _shtab_rns_page_node_cmdpath $candidate
            continue
          end
        end
        set -g _shtab_rns_page_node_npos (math $_shtab_rns_page_node_npos + 1)
    end
  end
end

# Condition helper: true if the current (sub)command path equals the given one.
function _shtab_rns_page_node_using
  _shtab_rns_page_node_scan
  test "$_shtab_rns_page_node_cmdpath" = "$argv"
end

set -g _shtab_rns_page_node_commands 
set -g _shtab_rns_page_node_opts_with_value --announce-interval --config --file-refresh-interval --files-dir --identity-dir --log-level --media-dir --node-name --page-refresh-interval --pages-dir -a -c -f -i -l -m -n -p

complete -c rns-page-node -e
complete -c rns-page-node -f

complete -c rns-page-node -n _shtab_rns_page_node_using -s h -l help -d 'show this help message and exit'
complete -c rns-page-node -n _shtab_rns_page_node_using -s c -l config -x -d 'Reticulum config path'
complete -c rns-page-node -n _shtab_rns_page_node_using -s p -l pages-dir -x -d 'Pages directory'
complete -c rns-page-node -n _shtab_rns_page_node_using -s f -l files-dir -x -d 'Files directory'
complete -c rns-page-node -n _shtab_rns_page_node_using -s m -l media-dir -x -d 'Media directory for images, defaults to pages directory'
complete -c rns-page-node -n _shtab_rns_page_node_using -s n -l node-name -x -d 'Node display name'
complete -c rns-page-node -n _shtab_rns_page_node_using -s a -l announce-interval -x -d 'Announce interval in minutes'
complete -c rns-page-node -n _shtab_rns_page_node_using -s i -l identity-dir -x -d 'Directory to store node identity'
complete -c rns-page-node -n _shtab_rns_page_node_using -l page-refresh-interval -x -d 'Page refresh interval in seconds, 0 disables auto-refresh'
complete -c rns-page-node -n _shtab_rns_page_node_using -l file-refresh-interval -x -d 'File refresh interval in seconds, 0 disables auto-refresh'
complete -c rns-page-node -n _shtab_rns_page_node_using -s l -l log-level -xka "DEBUG INFO WARNING ERROR CRITICAL" -d 'Logging level'
