# AUTOMATICALLY GENERATED by https://github.com/tqdm/shtab
# Usage:
# 1) Copy this to somewhere (e.g. ~/.local/share/tcsh_completion/rns-page-node).
# 2) Add the following line to your .cshrc or .tcshrc:
#    source ~/.local/share/tcsh_completion/rns-page-node
# See also: https://github.com/tcsh-org/tcsh/blob/master/complete.tcsh



complete rns-page-node \
        'c/-l=/(DEBUG INFO WARNING ERROR CRITICAL)/' \
        'c/--log-level=/(DEBUG INFO WARNING ERROR CRITICAL)/' \
        'c/--/(announce-interval config file-refresh-interval files-dir help identity-dir log-level media-dir node-name page-refresh-interval pages-dir)/' \
        'c/-/(- a c f h i l m n p)/' \
        'n/-l/(DEBUG INFO WARNING ERROR CRITICAL)/' \
        'n/--log-level/(DEBUG INFO WARNING ERROR CRITICAL)/' \
        'p/*/()/'